/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ManageAttachToPrivateNetworkRequest struct for ManageAttachToPrivateNetworkRequest
type ManageAttachToPrivateNetworkRequest struct {
	// Идентификатор VPS
	Id *string `json:"id,omitempty"`
	// Идентификатор сети
	NetworkId *string `json:"network_id,omitempty"`
	// желаемый ip-адрес. Если пустая строка, то выберется случайный
	Address *string `json:"address,omitempty"`
}

// NewManageAttachToPrivateNetworkRequest instantiates a new ManageAttachToPrivateNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageAttachToPrivateNetworkRequest() *ManageAttachToPrivateNetworkRequest {
	this := ManageAttachToPrivateNetworkRequest{}
	return &this
}

// NewManageAttachToPrivateNetworkRequestWithDefaults instantiates a new ManageAttachToPrivateNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageAttachToPrivateNetworkRequestWithDefaults() *ManageAttachToPrivateNetworkRequest {
	this := ManageAttachToPrivateNetworkRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManageAttachToPrivateNetworkRequest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageAttachToPrivateNetworkRequest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManageAttachToPrivateNetworkRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManageAttachToPrivateNetworkRequest) SetId(v string) {
	o.Id = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *ManageAttachToPrivateNetworkRequest) GetNetworkId() string {
	if o == nil || o.NetworkId == nil {
		var ret string
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageAttachToPrivateNetworkRequest) GetNetworkIdOk() (*string, bool) {
	if o == nil || o.NetworkId == nil {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *ManageAttachToPrivateNetworkRequest) HasNetworkId() bool {
	if o != nil && o.NetworkId != nil {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given string and assigns it to the NetworkId field.
func (o *ManageAttachToPrivateNetworkRequest) SetNetworkId(v string) {
	o.NetworkId = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ManageAttachToPrivateNetworkRequest) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageAttachToPrivateNetworkRequest) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ManageAttachToPrivateNetworkRequest) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ManageAttachToPrivateNetworkRequest) SetAddress(v string) {
	o.Address = &v
}

func (o ManageAttachToPrivateNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.NetworkId != nil {
		toSerialize["network_id"] = o.NetworkId
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableManageAttachToPrivateNetworkRequest struct {
	value *ManageAttachToPrivateNetworkRequest
	isSet bool
}

func (v NullableManageAttachToPrivateNetworkRequest) Get() *ManageAttachToPrivateNetworkRequest {
	return v.value
}

func (v *NullableManageAttachToPrivateNetworkRequest) Set(val *ManageAttachToPrivateNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManageAttachToPrivateNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManageAttachToPrivateNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageAttachToPrivateNetworkRequest(val *ManageAttachToPrivateNetworkRequest) *NullableManageAttachToPrivateNetworkRequest {
	return &NullableManageAttachToPrivateNetworkRequest{value: val, isSet: true}
}

func (v NullableManageAttachToPrivateNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageAttachToPrivateNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


