/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ManageStopVpsResponseError struct for ManageStopVpsResponseError
type ManageStopVpsResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewManageStopVpsResponseError instantiates a new ManageStopVpsResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageStopVpsResponseError() *ManageStopVpsResponseError {
	this := ManageStopVpsResponseError{}
	return &this
}

// NewManageStopVpsResponseErrorWithDefaults instantiates a new ManageStopVpsResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageStopVpsResponseErrorWithDefaults() *ManageStopVpsResponseError {
	this := ManageStopVpsResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ManageStopVpsResponseError) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageStopVpsResponseError) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ManageStopVpsResponseError) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ManageStopVpsResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ManageStopVpsResponseError) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageStopVpsResponseError) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ManageStopVpsResponseError) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ManageStopVpsResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ManageStopVpsResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableManageStopVpsResponseError struct {
	value *ManageStopVpsResponseError
	isSet bool
}

func (v NullableManageStopVpsResponseError) Get() *ManageStopVpsResponseError {
	return v.value
}

func (v *NullableManageStopVpsResponseError) Set(val *ManageStopVpsResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableManageStopVpsResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableManageStopVpsResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageStopVpsResponseError(val *ManageStopVpsResponseError) *NullableManageStopVpsResponseError {
	return &NullableManageStopVpsResponseError{value: val, isSet: true}
}

func (v NullableManageStopVpsResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageStopVpsResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


