/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ManageGetFileManagerSettingsResponse struct for ManageGetFileManagerSettingsResponse
type ManageGetFileManagerSettingsResponse struct {
	Credentials *ManageGetFileManagerSettingsResponseCredentials `json:"credentials,omitempty"`
	Error *ManageGetFileManagerSettingsResponseError `json:"error,omitempty"`
}

// NewManageGetFileManagerSettingsResponse instantiates a new ManageGetFileManagerSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageGetFileManagerSettingsResponse() *ManageGetFileManagerSettingsResponse {
	this := ManageGetFileManagerSettingsResponse{}
	return &this
}

// NewManageGetFileManagerSettingsResponseWithDefaults instantiates a new ManageGetFileManagerSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageGetFileManagerSettingsResponseWithDefaults() *ManageGetFileManagerSettingsResponse {
	this := ManageGetFileManagerSettingsResponse{}
	return &this
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *ManageGetFileManagerSettingsResponse) GetCredentials() ManageGetFileManagerSettingsResponseCredentials {
	if o == nil || o.Credentials == nil {
		var ret ManageGetFileManagerSettingsResponseCredentials
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageGetFileManagerSettingsResponse) GetCredentialsOk() (*ManageGetFileManagerSettingsResponseCredentials, bool) {
	if o == nil || o.Credentials == nil {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *ManageGetFileManagerSettingsResponse) HasCredentials() bool {
	if o != nil && o.Credentials != nil {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given ManageGetFileManagerSettingsResponseCredentials and assigns it to the Credentials field.
func (o *ManageGetFileManagerSettingsResponse) SetCredentials(v ManageGetFileManagerSettingsResponseCredentials) {
	o.Credentials = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ManageGetFileManagerSettingsResponse) GetError() ManageGetFileManagerSettingsResponseError {
	if o == nil || o.Error == nil {
		var ret ManageGetFileManagerSettingsResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageGetFileManagerSettingsResponse) GetErrorOk() (*ManageGetFileManagerSettingsResponseError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ManageGetFileManagerSettingsResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given ManageGetFileManagerSettingsResponseError and assigns it to the Error field.
func (o *ManageGetFileManagerSettingsResponse) SetError(v ManageGetFileManagerSettingsResponseError) {
	o.Error = &v
}

func (o ManageGetFileManagerSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Credentials != nil {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableManageGetFileManagerSettingsResponse struct {
	value *ManageGetFileManagerSettingsResponse
	isSet bool
}

func (v NullableManageGetFileManagerSettingsResponse) Get() *ManageGetFileManagerSettingsResponse {
	return v.value
}

func (v *NullableManageGetFileManagerSettingsResponse) Set(val *ManageGetFileManagerSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManageGetFileManagerSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManageGetFileManagerSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageGetFileManagerSettingsResponse(val *ManageGetFileManagerSettingsResponse) *NullableManageGetFileManagerSettingsResponse {
	return &NullableManageGetFileManagerSettingsResponse{value: val, isSet: true}
}

func (v NullableManageGetFileManagerSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageGetFileManagerSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


