/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StructuresIpInfo struct for StructuresIpInfo
type StructuresIpInfo struct {
	// Основной IP-адрес VPS
	Ip *string `json:"ip,omitempty"`
	// MAC-адрес
	Mac *string `json:"mac,omitempty"`
	// Идентификатор VPS, к которому привязан дополнительный IP-адрес
	VpsId *string `json:"vps_id,omitempty"`
}

// NewStructuresIpInfo instantiates a new StructuresIpInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructuresIpInfo() *StructuresIpInfo {
	this := StructuresIpInfo{}
	return &this
}

// NewStructuresIpInfoWithDefaults instantiates a new StructuresIpInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructuresIpInfoWithDefaults() *StructuresIpInfo {
	this := StructuresIpInfo{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *StructuresIpInfo) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresIpInfo) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *StructuresIpInfo) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *StructuresIpInfo) SetIp(v string) {
	o.Ip = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *StructuresIpInfo) GetMac() string {
	if o == nil || o.Mac == nil {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresIpInfo) GetMacOk() (*string, bool) {
	if o == nil || o.Mac == nil {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *StructuresIpInfo) HasMac() bool {
	if o != nil && o.Mac != nil {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *StructuresIpInfo) SetMac(v string) {
	o.Mac = &v
}

// GetVpsId returns the VpsId field value if set, zero value otherwise.
func (o *StructuresIpInfo) GetVpsId() string {
	if o == nil || o.VpsId == nil {
		var ret string
		return ret
	}
	return *o.VpsId
}

// GetVpsIdOk returns a tuple with the VpsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresIpInfo) GetVpsIdOk() (*string, bool) {
	if o == nil || o.VpsId == nil {
		return nil, false
	}
	return o.VpsId, true
}

// HasVpsId returns a boolean if a field has been set.
func (o *StructuresIpInfo) HasVpsId() bool {
	if o != nil && o.VpsId != nil {
		return true
	}

	return false
}

// SetVpsId gets a reference to the given string and assigns it to the VpsId field.
func (o *StructuresIpInfo) SetVpsId(v string) {
	o.VpsId = &v
}

func (o StructuresIpInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	if o.Mac != nil {
		toSerialize["mac"] = o.Mac
	}
	if o.VpsId != nil {
		toSerialize["vps_id"] = o.VpsId
	}
	return json.Marshal(toSerialize)
}

type NullableStructuresIpInfo struct {
	value *StructuresIpInfo
	isSet bool
}

func (v NullableStructuresIpInfo) Get() *StructuresIpInfo {
	return v.value
}

func (v *NullableStructuresIpInfo) Set(val *StructuresIpInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStructuresIpInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStructuresIpInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructuresIpInfo(val *StructuresIpInfo) *NullableStructuresIpInfo {
	return &NullableStructuresIpInfo{value: val, isSet: true}
}

func (v NullableStructuresIpInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructuresIpInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


