/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ManageGetAvailableSoftwareResponse struct for ManageGetAvailableSoftwareResponse
type ManageGetAvailableSoftwareResponse struct {
	Software *[]ManageGetAvailableSoftwareResponseSoftwareInfo `json:"software,omitempty"`
}

// NewManageGetAvailableSoftwareResponse instantiates a new ManageGetAvailableSoftwareResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageGetAvailableSoftwareResponse() *ManageGetAvailableSoftwareResponse {
	this := ManageGetAvailableSoftwareResponse{}
	return &this
}

// NewManageGetAvailableSoftwareResponseWithDefaults instantiates a new ManageGetAvailableSoftwareResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageGetAvailableSoftwareResponseWithDefaults() *ManageGetAvailableSoftwareResponse {
	this := ManageGetAvailableSoftwareResponse{}
	return &this
}

// GetSoftware returns the Software field value if set, zero value otherwise.
func (o *ManageGetAvailableSoftwareResponse) GetSoftware() []ManageGetAvailableSoftwareResponseSoftwareInfo {
	if o == nil || o.Software == nil {
		var ret []ManageGetAvailableSoftwareResponseSoftwareInfo
		return ret
	}
	return *o.Software
}

// GetSoftwareOk returns a tuple with the Software field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageGetAvailableSoftwareResponse) GetSoftwareOk() (*[]ManageGetAvailableSoftwareResponseSoftwareInfo, bool) {
	if o == nil || o.Software == nil {
		return nil, false
	}
	return o.Software, true
}

// HasSoftware returns a boolean if a field has been set.
func (o *ManageGetAvailableSoftwareResponse) HasSoftware() bool {
	if o != nil && o.Software != nil {
		return true
	}

	return false
}

// SetSoftware gets a reference to the given []ManageGetAvailableSoftwareResponseSoftwareInfo and assigns it to the Software field.
func (o *ManageGetAvailableSoftwareResponse) SetSoftware(v []ManageGetAvailableSoftwareResponseSoftwareInfo) {
	o.Software = &v
}

func (o ManageGetAvailableSoftwareResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Software != nil {
		toSerialize["software"] = o.Software
	}
	return json.Marshal(toSerialize)
}

type NullableManageGetAvailableSoftwareResponse struct {
	value *ManageGetAvailableSoftwareResponse
	isSet bool
}

func (v NullableManageGetAvailableSoftwareResponse) Get() *ManageGetAvailableSoftwareResponse {
	return v.value
}

func (v *NullableManageGetAvailableSoftwareResponse) Set(val *ManageGetAvailableSoftwareResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManageGetAvailableSoftwareResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManageGetAvailableSoftwareResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageGetAvailableSoftwareResponse(val *ManageGetAvailableSoftwareResponse) *NullableManageGetAvailableSoftwareResponse {
	return &NullableManageGetAvailableSoftwareResponse{value: val, isSet: true}
}

func (v NullableManageGetAvailableSoftwareResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageGetAvailableSoftwareResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


