/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StructuresOperatingSystemRequirements struct for StructuresOperatingSystemRequirements
type StructuresOperatingSystemRequirements struct {
	// Количество ядер процессора, шт
	CpuCount *int32 `json:"cpu_count,omitempty"`
	// Размер диска, мб
	DiskSize *int32 `json:"disk_size,omitempty"`
	// Объем оперативной памяти, мб
	Memory *int32 `json:"memory,omitempty"`
}

// NewStructuresOperatingSystemRequirements instantiates a new StructuresOperatingSystemRequirements object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructuresOperatingSystemRequirements() *StructuresOperatingSystemRequirements {
	this := StructuresOperatingSystemRequirements{}
	return &this
}

// NewStructuresOperatingSystemRequirementsWithDefaults instantiates a new StructuresOperatingSystemRequirements object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructuresOperatingSystemRequirementsWithDefaults() *StructuresOperatingSystemRequirements {
	this := StructuresOperatingSystemRequirements{}
	return &this
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *StructuresOperatingSystemRequirements) GetCpuCount() int32 {
	if o == nil || o.CpuCount == nil {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresOperatingSystemRequirements) GetCpuCountOk() (*int32, bool) {
	if o == nil || o.CpuCount == nil {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *StructuresOperatingSystemRequirements) HasCpuCount() bool {
	if o != nil && o.CpuCount != nil {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *StructuresOperatingSystemRequirements) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetDiskSize returns the DiskSize field value if set, zero value otherwise.
func (o *StructuresOperatingSystemRequirements) GetDiskSize() int32 {
	if o == nil || o.DiskSize == nil {
		var ret int32
		return ret
	}
	return *o.DiskSize
}

// GetDiskSizeOk returns a tuple with the DiskSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresOperatingSystemRequirements) GetDiskSizeOk() (*int32, bool) {
	if o == nil || o.DiskSize == nil {
		return nil, false
	}
	return o.DiskSize, true
}

// HasDiskSize returns a boolean if a field has been set.
func (o *StructuresOperatingSystemRequirements) HasDiskSize() bool {
	if o != nil && o.DiskSize != nil {
		return true
	}

	return false
}

// SetDiskSize gets a reference to the given int32 and assigns it to the DiskSize field.
func (o *StructuresOperatingSystemRequirements) SetDiskSize(v int32) {
	o.DiskSize = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *StructuresOperatingSystemRequirements) GetMemory() int32 {
	if o == nil || o.Memory == nil {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresOperatingSystemRequirements) GetMemoryOk() (*int32, bool) {
	if o == nil || o.Memory == nil {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *StructuresOperatingSystemRequirements) HasMemory() bool {
	if o != nil && o.Memory != nil {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *StructuresOperatingSystemRequirements) SetMemory(v int32) {
	o.Memory = &v
}

func (o StructuresOperatingSystemRequirements) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CpuCount != nil {
		toSerialize["cpu_count"] = o.CpuCount
	}
	if o.DiskSize != nil {
		toSerialize["disk_size"] = o.DiskSize
	}
	if o.Memory != nil {
		toSerialize["memory"] = o.Memory
	}
	return json.Marshal(toSerialize)
}

type NullableStructuresOperatingSystemRequirements struct {
	value *StructuresOperatingSystemRequirements
	isSet bool
}

func (v NullableStructuresOperatingSystemRequirements) Get() *StructuresOperatingSystemRequirements {
	return v.value
}

func (v *NullableStructuresOperatingSystemRequirements) Set(val *StructuresOperatingSystemRequirements) {
	v.value = val
	v.isSet = true
}

func (v NullableStructuresOperatingSystemRequirements) IsSet() bool {
	return v.isSet
}

func (v *NullableStructuresOperatingSystemRequirements) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructuresOperatingSystemRequirements(val *StructuresOperatingSystemRequirements) *NullableStructuresOperatingSystemRequirements {
	return &NullableStructuresOperatingSystemRequirements{value: val, isSet: true}
}

func (v NullableStructuresOperatingSystemRequirements) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructuresOperatingSystemRequirements) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


